export const idols = [{
    id: 0,
    stageName: 'Sana',
    nationality: 'Japanese',
    group: 'Twice',
    mbti: 'ENFP',
    height: '168',
    weight: '47',
    imageId: 'UYzIuvq'
}, {
    id: 1,
    stageName: 'Sua',
    nationality: 'Korean',
    group: 'Dreamcatcher',
    mbti: 'ESFJ',
    height: '162',
    weight: '42',
    imageId: '9MzVCZu'
}, {
    id: 2,
    stageName: 'Jiu',
    nationality: 'Korean',
    group: 'Dreamcatcher',
    mbti: 'ENFP',
    height: '167',
    weight: '49',
    imageId: 'ApyIZ9q'
}, {
    id: 3,
    stageName: 'Seulgi',
    nationality: 'Korean',
    group: 'Red Velvet',
    mbti: 'ISFP',
    height: '164',
    weight: '44',
    imageId: 'ZnoPg4l'
}, {
    id: 4,
    stageName: 'Miyeon',
    nationality: 'Korean',
    group: '(G)-IDLE',
    mbti: 'ENFP',
    height: '161',
    weight: '45',
    imageId: 'i85T0v3'
}, {
    id: 5,
    stageName: 'Momo',
    nationality: 'Japanese',
    group: 'Twice',
    mbti: 'INFP',
    height: '167',
    weight: '48.5',
    imageId: '6NapGJW'
}, {
    id: 6,
    stageName: 'Handong',
    nationality: 'Chinese',
    group: 'Dreamcatcher',
    mbti: 'ISFP',
    height: '165',
    weight: '46',
    imageId: 'mN9sFdK'
}];